version: '3.8'

services:
  chat-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/data/chat.db
    volumes:
      - chat_data:/app/data
    restart: unless-stopped

volumes:
  chat_data:
    driver: local 